// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package mineFs_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockMeta struct {
	BlockId              int64    `protobuf:"varint,1,opt,name=block_id,json=blockId" json:"block_id,omitempty"`
	BlockSize            int64    `protobuf:"varint,2,opt,name=block_size,json=blockSize" json:"block_size,omitempty"`
	Checksum             int64    `protobuf:"varint,3,opt,name=checksum" json:"checksum,omitempty"`
	Version              int64    `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	StorePath            string   `protobuf:"bytes,5,opt,name=store_path,json=storePath" json:"store_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMeta) Reset()         { *m = BlockMeta{} }
func (m *BlockMeta) String() string { return proto.CompactTextString(m) }
func (*BlockMeta) ProtoMessage()    {}
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_43cda5ee4f6790e1, []int{0}
}
func (m *BlockMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMeta.Unmarshal(m, b)
}
func (m *BlockMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMeta.Marshal(b, m, deterministic)
}
func (dst *BlockMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMeta.Merge(dst, src)
}
func (m *BlockMeta) XXX_Size() int {
	return xxx_messageInfo_BlockMeta.Size(m)
}
func (m *BlockMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMeta.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMeta proto.InternalMessageInfo

func (m *BlockMeta) GetBlockId() int64 {
	if m != nil {
		return m.BlockId
	}
	return 0
}

func (m *BlockMeta) GetBlockSize() int64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *BlockMeta) GetChecksum() int64 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

func (m *BlockMeta) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockMeta) GetStorePath() string {
	if m != nil {
		return m.StorePath
	}
	return ""
}

func init() {
	proto.RegisterType((*BlockMeta)(nil), "mineFs.proto.BlockMeta")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_block_43cda5ee4f6790e1) }

var fileDescriptor_block_43cda5ee4f6790e1 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xca, 0xc9, 0x4f,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc9, 0xcd, 0xcc, 0x4b, 0x75, 0x2b, 0x86,
	0xf0, 0x94, 0x66, 0x31, 0x72, 0x71, 0x3a, 0x81, 0x64, 0x7d, 0x53, 0x4b, 0x12, 0x85, 0x24, 0xb9,
	0x38, 0xc0, 0x4a, 0xe3, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xd8, 0xc1, 0x7c,
	0xcf, 0x14, 0x21, 0x59, 0x2e, 0x2e, 0x88, 0x54, 0x71, 0x66, 0x55, 0xaa, 0x04, 0x13, 0x58, 0x92,
	0x13, 0x2c, 0x12, 0x9c, 0x59, 0x95, 0x2a, 0x24, 0xc5, 0xc5, 0x91, 0x9c, 0x91, 0x9a, 0x9c, 0x5d,
	0x5c, 0x9a, 0x2b, 0xc1, 0x0c, 0x96, 0x84, 0xf3, 0x85, 0x24, 0xb8, 0xd8, 0xcb, 0x52, 0x8b, 0x8a,
	0x33, 0xf3, 0xf3, 0x24, 0x58, 0x20, 0x86, 0x42, 0xb9, 0x20, 0x43, 0x8b, 0x4b, 0xf2, 0x8b, 0x52,
	0xe3, 0x0b, 0x12, 0x4b, 0x32, 0x24, 0x58, 0x15, 0x18, 0x35, 0x38, 0x83, 0x38, 0xc1, 0x22, 0x01,
	0x89, 0x25, 0x19, 0x49, 0x6c, 0x60, 0x37, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x32, 0x7f,
	0x73, 0x38, 0xc0, 0x00, 0x00, 0x00,
}
