// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package mineFs_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Version              uint64   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Mode                 int32    `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
	Blocks               int64    `protobuf:"varint,4,opt,name=blocks" json:"blocks,omitempty"`
	Ctime                uint32   `protobuf:"varint,5,opt,name=ctime" json:"ctime,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,7,opt,name=size" json:"size,omitempty"`
	Replicas             int32    `protobuf:"varint,8,opt,name=replicas" json:"replicas,omitempty"`
	ParentEntryId        int64    `protobuf:"varint,9,opt,name=parent_entry_id,json=parentEntryId" json:"parent_entry_id,omitempty"`
	Owner                int32    `protobuf:"varint,10,opt,name=owner" json:"owner,omitempty"`
	CsAddrs              []string `protobuf:"bytes,11,rep,name=cs_addrs,json=csAddrs" json:"cs_addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_0a4919f3fb79406a, []int{0}
}
func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (dst *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(dst, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FileInfo) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FileInfo) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileInfo) GetBlocks() int64 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

func (m *FileInfo) GetCtime() uint32 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetReplicas() int32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *FileInfo) GetParentEntryId() int64 {
	if m != nil {
		return m.ParentEntryId
	}
	return 0
}

func (m *FileInfo) GetOwner() int32 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *FileInfo) GetCsAddrs() []string {
	if m != nil {
		return m.CsAddrs
	}
	return nil
}

func init() {
	proto.RegisterType((*FileInfo)(nil), "mineFs.proto.FileInfo")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_file_0a4919f3fb79406a) }

var fileDescriptor_file_0a4919f3fb79406a = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x49, 0xa7, 0xbf, 0x57, 0x47, 0x21, 0x88, 0x5c, 0x5d, 0x05, 0x17, 0x92, 0x95, 0x1b,
	0x9f, 0xc0, 0x85, 0x03, 0xb3, 0xcd, 0x0b, 0x94, 0x4e, 0x73, 0x07, 0x2e, 0xb6, 0x49, 0x49, 0x8a,
	0xa2, 0xaf, 0xe1, 0x0b, 0x4b, 0x52, 0x75, 0x77, 0xbe, 0x0f, 0xce, 0x49, 0xb8, 0x00, 0x67, 0x9e,
	0xe8, 0x69, 0x09, 0x7e, 0xf5, 0xf2, 0x72, 0x66, 0x47, 0x87, 0xb8, 0xd1, 0xc3, 0x77, 0x01, 0xed,
	0x81, 0x27, 0x3a, 0xba, 0xb3, 0x97, 0x57, 0x50, 0xb0, 0x45, 0xa1, 0x84, 0x2e, 0x4d, 0xc1, 0x56,
	0x22, 0x34, 0xef, 0x14, 0x22, 0x7b, 0x87, 0x45, 0x96, 0x7f, 0x28, 0x25, 0x94, 0xb3, 0xb7, 0x84,
	0x3b, 0x25, 0x74, 0x65, 0x72, 0x96, 0xb7, 0x50, 0x9f, 0x26, 0x3f, 0xbe, 0x45, 0x2c, 0x95, 0xd0,
	0x3b, 0xf3, 0x4b, 0xf2, 0x06, 0xaa, 0x71, 0xe5, 0x99, 0xb0, 0x52, 0x42, 0xef, 0xcd, 0x06, 0x69,
	0xc1, 0x0d, 0x33, 0x61, 0xad, 0x84, 0xee, 0x4c, 0xce, 0xc9, 0x45, 0xfe, 0x22, 0x6c, 0x72, 0x3f,
	0x67, 0x79, 0x0f, 0x6d, 0xa0, 0x65, 0xe2, 0x71, 0x88, 0xd8, 0xe6, 0xd7, 0xfe, 0x59, 0x3e, 0xc2,
	0xf5, 0x32, 0x04, 0x72, 0x6b, 0x4f, 0x6e, 0x0d, 0x9f, 0x3d, 0x5b, 0xec, 0x72, 0x75, 0xbf, 0xe9,
	0xd7, 0x64, 0x8f, 0x36, 0xfd, 0xc0, 0x7f, 0x38, 0x0a, 0x08, 0x79, 0x60, 0x03, 0x79, 0x07, 0xed,
	0x18, 0xfb, 0xc1, 0xda, 0x10, 0xf1, 0x42, 0xed, 0x74, 0x67, 0x9a, 0x31, 0xbe, 0x24, 0x3c, 0xd5,
	0xf9, 0x38, 0xcf, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x37, 0x79, 0x9b, 0x38, 0x01, 0x00,
	0x00,
}
